/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./src/components/Header.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpChromeFilled: typeof import('~icons/ep/chrome-filled')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
  }
}
