// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName() {
  return window['go']['backend']['MainApp']['GetAppName']();
}

export function Greet(arg1) {
  return window['go']['backend']['MainApp']['Greet'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['MainApp']['Startup'](arg1);
}
